name: Terraform-GitHub-Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
  AWS_SESSION_TOKEN: ${{ secrets.aws_session_token }}
#  AWS_PUBLIC_KEY: ${{ secrets.aws_public_key }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Plan
        id: plan
        run: terraform plan
      
      - name: Terraform Apply
        env:
          TF_VAR_public_key: ${{ secrets.AWS_PUBLIC_KEY }}
        id: apply
        run: terraform apply --auto-approve
