name: Terraform-GitHub-Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
  AWS_SESSION_TOKEN: ${{ secrets.aws_session_token }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "public_key<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.AWS_PUBLIC_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "private_key<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.AWS_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Debug Environment Variables
        run: env | grep '_KEY'
        
      - name: Terraform Plan
        id: plan
        run: |
          export TF_LOG=DEBUG
          terraform plan -out=plan.out -no-color \
            -var="public_key=${{ secrets.AWS_PUBLIC_KEY }}" \
            -var="private_key=${{ secrets.AWS_PRIVATE_KEY }}"
          terraform show -no-color plan.out
      
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve plan.out
